"""replace videos with polymorphic titles

Revision ID: f7e71a10bbd5
Revises: af3c98da29b9
Create Date: 2026-05-25 20:37:46.513154+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7e71a10bbd5'
down_revision: str | None = 'af3c98da29b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('type', sa.Enum('MOVIE', 'SERIES', 'SEASON', 'EPISODE', 'SUPPLEMENTAL', name='title_type'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Enum('ER', 'L', 'AGE_10', 'AGE_12', 'AGE_14', 'AGE_16', 'AGE_18', name='title_rating'), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_parent_id'), 'titles', ['parent_id'], unique=False)
    op.create_index(op.f('ix_titles_title'), 'titles', ['title'], unique=False)
    op.create_index(op.f('ix_titles_type'), 'titles', ['type'], unique=False)
    op.create_table('title_cast_member',
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('cast_member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'cast_member_id')
    )
    op.create_table('title_category',
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'category_id')
    )
    op.create_table('title_genre',
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'genre_id')
    )
    op.drop_table('video_category')
    op.drop_table('video_cast_member')
    op.drop_table('video_genre')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_genre',
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('video_genre_genre_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_genre_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'genre_id', name=op.f('video_genre_pkey'))
    )
    op.create_table('video_cast_member',
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cast_member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], name=op.f('video_cast_member_cast_member_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_cast_member_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'cast_member_id', name=op.f('video_cast_member_pkey'))
    )
    op.create_table('videos',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=4000), autoincrement=False, nullable=False),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', postgresql.ENUM('ER', 'L', 'AGE_10', 'AGE_12', 'AGE_14', 'AGE_16', 'AGE_18', name='video_rating'), autoincrement=False, nullable=False),
    sa.Column('opened', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('videos_pkey'))
    )
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_table('video_category',
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('video_category_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_category_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'category_id', name=op.f('video_category_pkey'))
    )
    op.drop_table('title_genre')
    op.drop_table('title_category')
    op.drop_table('title_cast_member')
    op.drop_index(op.f('ix_titles_type'), table_name='titles')
    op.drop_index(op.f('ix_titles_title'), table_name='titles')
    op.drop_index(op.f('ix_titles_parent_id'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
